name = "Harmony"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31543c56bbe439739f43d39d89d4e24128c090be192c4bf303fbcaa546746cb4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
